# Generated by Django 4.2.4 on 2023-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_slaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='_storage/media/home/en/')),
                ('title', models.CharField(max_length=99)),
                ('active', models.CharField(choices=[(1, 'no'), (2, 'yes')], default=2, max_length=50)),
            ],
        ),
    ]
