# Generated by Django 4.2.4 on 2023-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0002_alter_home_slaid_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='home_slaid',
            name='active',
            field=models.CharField(choices=[('no', 'no'), ('active', 'active')], max_length=50),
        ),
    ]
