# Generated by Django 4.2.4 on 2023-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0006_motto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='_storage/media/video/en/')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
