# Generated by Django 4.2.4 on 2023-08-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='_storage/media/en/product/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('two_images', models.ImageField(upload_to='_storage/media/en/product/two/')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='images',
            field=models.ImageField(upload_to='_storage/media/en/about/'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='images',
            field=models.ImageField(upload_to='_storage/media/en/motto/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='images',
            field=models.ImageField(upload_to='_storage/media/en/video/'),
        ),
    ]
