# Generated by Django 4.2.4 on 2023-08-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0009_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_about',
            name='text',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
    ]
