# Generated by Django 4.2.4 on 2023-08-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0010_product_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='_storage/media/en/certificate/')),
            ],
        ),
    ]
